### ISSUE TITLE
Changing nested GAFMovieClip's child position resets its transformations.

### ISSUE THREAD

**Issue by avstudios** [bp74/StageXL_GAF#1]
Hi Bernhard,
When I set the position of a nested child in MovieClip then the child's transformationMatrix is reset.
I'm not sure if it's a bug or it's not a good idea to create root GAFMovieClip that contains MovieClips or Sprites and then manipulate them using Tween library?

**Comment by bp74** [comment]
Hi, yes this is the way how it works. Please take a look at this line:
https://github.com/bp74/StageXL_GAF/blob/master/lib/src/display/gaf_movie_clip.dart#L514

GAF directly sets the transformationMatrix of the DisplayObject, without updating the x, y, rotate, etc. properties. As soon as you set one of those properties, a new transformationMatrix based on those properties is calculated.

The only way around this issue would be to update x, y, scaleX, scaleY, skewX, skewY, pivotX, pivotY and rotate on every transformationMatrix update. This would work, but would cause quite a lot of CPU load. Maybe it would be worth to introduce an option to do this.

**Comment by bp74** [comment]
A quick solution would be to write that code on your own, and update all those properties based on the transformationMatrix before you set one of the properties in your code. Like this:

    reverseTransformationMatrix(displayObject); // updates all properties based on current transformationMatrix
    displayObject.x += 10;
    displayObject.y += 10;

**Comment by bp74** [comment]
Starling does this:
https://github.com/Gamua/Starling-Framework/blob/master/starling/src/starling/display/DisplayObject.as#L797

**Comment by avstudios** [comment]
Thanks. That was very quick feedback :) I'm looking for some simple solution at the moment and the performance is very important. I will separate the clips and add them manually to the parent clip. 
As I remember it was possible with Toolkit for Dart so I hoped I can do it with GAF. 
Anyway, thanks again for explaining it to me.
